### ISSUE TITLE
How to run the Server in VS2019?

### ISSUE THREAD

**Issue by win32nipuh** [dotnet-presentations/blazor-workshop#182]
I have built the solution in VS2019, then run BlazingPizza Server Debug, the console started ok. And Edge has appeared with address http://localhost:64590/
but it gives an error:

>  This site can’t provide a secure connectionlocalhost sent an invalid response.
> Try running Windows Network Diagnostics.
> ERR_SSL_PROTOCOL_ERROR

How to fix it?

**Comment by safoli** [comment]
set "sslPort": 44366 in launchSettings.json files (client and server proj) worked for me.

**Comment by yopez83** [comment]
I'd say you have selected the profile BlazinPizza.Server to debug, reason why you're running on a different port (64590). Now, I've switched my Debugger profile from IISExpress, which runs on port 64589, to BlazingPizza.Server to see if I get the same error, and I didn't. However the page never finishes loading. I'd say this has to do with the fact (you mentioned above) you're running on Edge, rather than Chrome or [Microsoft Edge Dev](https://developer.microsoft.com/en-us/microsoft-edge/). Suggestions,
- I would change the Web Browser from the debugger profile to either Chrome or Microsoft Edge Dev (if you downloaded). Then follow the instructions for debugging.

**Comment by SteveSandersonMS** [comment]
Hopefully the question is answered.
