### ISSUE TITLE
How to configure Twitter Keys

### ISSUE THREAD

**Issue by simonhamelech** [dotnet-presentations/blazor-workshop#184]
Could you add some screen shots showing how to configure new keys from the Twitter developer console

**Comment by mvnoppen** [comment]
I was wondering the same thing. I created a Twitter Dev account and I have the keys, but I get a 403 (Forbidden) Response when using my keys. I think it has something to do with the CallbackURL I definded in the Twitter application, but I'm not sure if that's the problem.

**Comment by yopez83** [comment]
Once logged on:

- navigate to the [apps](https://developer.twitter.com/en/apps) page. You should find a button called `Create an app` to the right hand side (see below). Click on it.
![image](https://user-images.githubusercontent.com/12285372/72858322-696d1300-3c8e-11ea-97c7-918eb136bceb.png).
- Then fill in with the appropriate information. Keep in mind the **Website URL** field needs a valid domain, do not use localhost here.
![image](https://user-images.githubusercontent.com/12285372/72858606-59a1fe80-3c8f-11ea-9933-9c62316d8252.png)
- Continue filling in the information as below. Please note, you can as many URLs as you want, either http or https or both. Most importantly, have used ports `50001` and `50002`, but there is not restriction, you can use the numbers you prefer.
![image](https://user-images.githubusercontent.com/12285372/72858694-a38ae480-3c8f-11ea-8b01-8a5132e2419e.png)
- Provide a description and hit `Create`.
![image](https://user-images.githubusercontent.com/12285372/72858988-6ecb5d00-3c90-11ea-8e11-0f075022d5b7.png)
- You should have now a new app similar to the one below. Click the `Details` button from the right.
![image](https://user-images.githubusercontent.com/12285372/72859107-b6ea7f80-3c90-11ea-9170-f3ce13d44dbc.png)
- Click the `Keys and tokens` tab and copy your API key and API secret key values. 
![image](https://user-images.githubusercontent.com/12285372/72859360-8a833300-3c91-11ea-994f-1ebbd999ad68.png)
- Replace the values below from the `appsettings.Development.json` with the values you copied.
```jsonc
  "Authentication": {
    "Twitter": {
      "ConsumerKey": "U9DbAaVcDPYO3RVFlDo4w",
      "ConsumerSecret": "l6HWZa8F5MJmbBkGSzL6gMjgZMererT5KROxAzws9o"
    }
```
**Note:** Make sure your project URL(s) matches the **Callback URL** you provided in the Twitter app. Otherwise, it won't work.

**Comment by SteveSandersonMS** [comment]
Thanks for answering, @yopez83!
