### ISSUE TITLE
Why use the OnInitialized method instead of the OnInitializedAsync method in the Checkout.razor component?

### ISSUE THREAD

**Issue by ltm0203** [dotnet-presentations/blazor-workshop#239]
This Repo is really great and has helped me solve a lot of problems,
 but I also get questions like the title when I reference the code.

Why use  OnInitialized method ?

What is the purpose of this ` _ `?

```
protected override  void OnInitialized()
	{
		// In the background, ask if they want to be notified about order updates
		_ = RequestNotificationSubscriptionAsync();
	}
	
```
I think the usage should be to use the asynchronous method, not the synchronous
```
protected override async Task OnInitializedAsync()
	{
			await		RequestNotificationSubscriptionAsync();
	}
```

**Comment by lohithgn** [comment]
@ltm0203 

By looking at the history of the code commits - this was coded by @SteveSandersonMS. I am guessing here as to what might be his intention:
If you look at the RequestNotificationSubscriptionAsync() code:
```
    async Task RequestNotificationSubscriptionAsync()
    {
        var subscription = await JSRuntime.InvokeAsync<NotificationSubscription>("blazorPushNotifications.requestSubscription");
        if (subscription != null)
        {
            try
            {
                await OrdersClient.SubscribeToNotifications(subscription);
            }
            catch (AccessTokenNotAvailableException ex)
            {
                ex.Redirect();
            }
        }
    }
    ```
It's just invoking the service worker's push manager and creating a new subscription. Since this is all in the background and I don't need to wait for what happens inside RequestNotificationSubscriptionAsync() - we have OnInitialized() being used. If there is a need for you to await - you should use OnInitializedAasync() method. This is my guess.

If @SteveSandersonMS  sees this - he can comment on the choice of OnInitialized() vs OnInitializedAsync()  😄
