### ISSUE TITLE
app.UseClientSideBlazor<TStartup>() before or after app.UseRouting()?

### ISSUE THREAD

**Issue by MaherJendoubi** [dotnet-presentations/blazor-workshop#94]
Hi @SteveSandersonMS,

I am a little confused about this :

In one hand :
Remove any call to app.UseBlazor<TStartup>() and instead add a call to app.UseClientSideBlazor<TStartup>() before the call to app.UseRouting(). Also add a call to endpoints.MapFallbackToClientSideBlazor<TStartup>("index.html") in the call to app.UseEndpoints().

            `app.UseClientSideBlazorFiles<Client.Startup>();
            app.UseRouting();
            app.UseAuthentication();
            app.UseAuthorization();            

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
                endpoints.MapFallbackToClientSideBlazor<Client.Startup>("index.html");
            });`

https://devblogs.microsoft.com/aspnet/asp-net-core-and-blazor-updates-in-net-core-3-0-preview-6/

In the other hand:

            `app.UseRouting();
            app.UseAuthentication();
            app.UseAuthorization();
            app.UseClientSideBlazorFiles<Client.Startup>();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
                endpoints.MapFallbackToClientSideBlazor<Client.Startup>("index.html");
            });`

https://github.com/dotnet-presentations/blazor-workshop/blob/b6c29b13e374d68e9f613251e7dab1cad18f1bd2/src/BlazingPizza.Server/Startup.cs

Thanks,
Maher

**Comment by longhornleads** [comment]
I cannot get past this error right now using the latest VS 2019 preview and trying to build and debug your solution "Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'IApplicationBuilder' does not contain a definition for 'UseAuthorization' and no accessible extension method 'UseAuthorization' accepting a first argument of type 'IApplicationBuilder' could be found (are you missing a using directive or an assembly reference?)	BlazingPizza.Server	C:\Users\kenne\OneDrive\Desktop\blazor-workshop-master\blazor-workshop-master\src\BlazingPizza.Server\Startup.cs	69	Active"

**Comment by SteveSandersonMS** [comment]
> I hope they stabilize it a little more

Once we ship 3.0 (a few months from now), we turn stability mode on. From that date, it gets *really*, **really** stable, even to the point we might be unable to fix things we really want to. We're very serious about backward-compatibility.

But until then, we will keep changing everything we think needs to be changed, because if we don't it's going to get stuck that way forever once 3.0 ships :)

> I cannot get past this error right now using the latest VS 2019 preview and trying to build and debug your solution

Sounds like you're running an incorrect SDK version or haven't restored dependencies properly. This code certainly works with the latest 3.0 preview 6 SDK and VS preview, since that's how we delivered the workshop last week, and all 30 or so people in the class had it working fine. I'd recommend starting from a clean checkout after making sure you have the preview 6 SDK and VS preview.

**Comment by danroth27** [comment]
This issue is pretty stale and the API has moved around a bit, so I'm going to go ahead and close this.
